---
- name: Spawn PiHole Container
  docker_container:
    name: pihole
    image: pihole/pihole:latest
    restart_policy: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8787:80/tcp"
      - "8788:443/tcp"

    env: 
      PIHOLE_DNS_: "{{ dnscrypt_container_ipv4 }}#5300"
    networks:
      - name: "{{ traefik_network_name }}"
      - name: "{{ pihole_network_name }}"
        ipv4_address: "{{ pihole_container_ipv4 }}"
    volumes: 
      - "{{ pihole_root}}/etc-pihole:/etc/pihole/"
      - "{{ pihole_root}}/etc-dnsmasq.d/:/etc/dnsmasq.d/"
    labels:
      traefik.enable: "true"
      traefik.http.routers.pihole-web.rule: Host("pihole.horse")
      traefik.http.routers.pihole-web.entrypoints: web
      traefik.http.services.pihole-web.loadbalancer.server.port: "80"
      # traefik.tcp.routers.pihole-dns.rule: HostSNI("*")
      # traefik.udp.routers.pihole-dns.rule: HostSNI("*")
      # traefik.udp.routers.pihole-dns.entrypoints: dns
      # traefik.tcp.routers.pihole-dns.entrypoints: dns
      traefik.docker.network: "{{ traefik_network_name }}"