---
- name: Create hass network 
  docker_network: 
    name: "{{ hass_network_name }}"
    driver: bridge
    ipam_config:
      - subnet: "{{ hass_subnet }}"

- name: spawn Home Assitant
  docker_container: 
    name: homeassitant
    image: "homeassistant/home-assistant"
    restart_policy: unless-stopped
    volumes:
      - "{{ automation_root }}/homeassitant/config:/config/"
    ports:
      - "8123:8123"
    networks:
      - name: "{{ traefik_network_name }}"
      - name: "{{ hass_network_name }}"
        ipv4_address: "{{ hass_container_ipv4 }}"
    dns_servers: 
      - 1.1.1.1
    labels:
      traefik.enable: "true"
      traefik.http.routers.hass.rule: Host("hass.horse")
      traefik.http.routers.hass.entrypoints: web
      traefik.http.services.hass.loadbalancer.server.port: "8123"
      traefik.docker.network: "{{ traefik_network_name }}"