---


- name: Install Virt Stuff
  become: true
  package:
    name: "{{ virt_packages }}"
    state: present
    
- name: Enable and start libvirt
  become: true
  service:
    name: libvirtd
    state: started
    enabled: true



- name: Disable network virsh
  community.libvirt.virt_net:
    command: destroy
    name: default 
    autostart: false
