---
- name: Copy prometheus config
  become: true
  template:
    src: files/prometheus.yml.j2
    dest: "{{ monitoring_root }}/prometheus/config/prometheus.yml"
    mode: 0775

- name: change prometheus config directory permissions
  become: true
  file:
    path: "{{ monitoring_root }}/prometheus"
    state: directory
    mode: '0777'
    recurse: true

- name: Spawn Prometheus container
  docker_container:
    name: "{{ prometheus_container_name }}"
    image: prom/prometheus:latest
    restart_policy: unless-stopped
    volumes:
      - "{{ monitoring_root }}/prometheus/config:/etc/prometheus/"
      - "{{ monitoring_root }}/prometheus/data:/prometheus"
      # - "/home/lin/prometheus/data:/prometheus"
    user: "1000:1000"
    ports:
      - "9090:9090"
    networks:
      - name: "{{ traefik_network_name }}"
      - name: "{{ monitoring_network_name }}"
        ipv4_address: "{{ monitoring_prometheus_container_ipv4 }}"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'