- name: Mount the data drives
  mount:
    name: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: xfs
    state: mounted
    passno: "2"
  with_items: "{{ disks }}"
  when: disks[0] is defined



- name: Mount the mergerfs array
  mount:
    name: "{{ mergerfs_root }}"
    src: /mnt/pool/disk*
    opts: direct_io,defaults,allow_other,moveonenospc=1,minfreespace=22G,fsname=mergerfs_slow,uid=1000,gid=1000
    fstype: fuse.mergerfs
    state: mounted
  when: disks[0] is defined