
#
# network stuff
#

lan_network: "192.168.15.0"

host_ip: "192.168.15.167"




# - docker network


# - traefik network stuff
traefik_network_name: traefik_default

traefik_subnet: "172.18.0.0/24"

traefik_controller_ipv4: "172.18.0.200"

# - pihole network stuff
pihole_network_name: pihole_network

pihole_subnet: '10.0.1.0/24'

pihole_container_ipv4: 10.0.1.3

dnscrypt_container_ipv4: 10.0.1.2

# - home assitant network stuff

hass_network_name: hass_network

hass_subnet: '10.0.2.0/24'

hass_container_ipv4: 10.0.2.2

hass_mqtt_container_ipv4: 10.0.2.3


hass_nodered_container_ipv4: 10.0.2.4
#
# main variables
#


username: "lin"

arch: amd64
email: lin@fnxln.com


version: jammy

shell: /bin/zsh
apt_mirror: http://ubuntu.c3sl.ufpr.br/ubuntu/

timezone: Brazil/East
locale: pt_BR.UTF-8
ntp_timezone: '{{ timezone }}'
docker_dir: /opt/docker/data
dns_nameservers: ['1.1.1.1', '1.0.0.1']


extra_packages:
  - zsh
  - net-tools
  - htop
  - speedtest-cli
  - git
  - neofetch
  - rsync
  - lm-sensors
  - iotop
  - neovim


#
# SSH (geerlingguy.security)
#
security_ssh_port: 2244

security_sudoers_passwordless: ['{{ username }}']

security_autoupdate_reboot: true

security_autoupdate_mail_to: '{{ email }}'

security_autoupdate_reboot_time: '23:00'

security_autoupdate_mail_on_error: false

#enables

enalbe_storage_stuff: true


# virt stuff
enable_virt_stuff: true

virt_packages:
  - libvirt-daemon-system
  - qemu-kvm
  - ovmf
  - python3-lxml
  - python3-libvirt

  
# nas stuff

mergerfs_root: /mnt/storage
disks:
  - src: /dev/vdb1
    path: /mnt/pool/disk1
  - src: /dev/vdc1
    path: /mnt/pool/disk2    

# paths

storage_root: "{{ mergerfs_root }}"
docker_root: "{{ storage_root }}/Docker"


# container stuff


enable_homeautomation: true

pihole_root: "{{ docker_root }}/PiHole"
automation_root: "{{ docker_root }}/Automation"