---
- name: Create a network
  docker_network:
    name: "{{ traefik_network_name }}"
    driver: bridge
    ipam_config:
      - subnet: "{{ traefik_subnet }}"

- name: Spawn traefik
  docker_container:
    name: "{{ container_name }}"
    image: "traefik:v2.8"
    restart_policy: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      # - "--entrypoints.web.redirect.scheme=https"
      - "--entrypoints.websecure.address=:443"
      # - "--entrypoints.dns.address=:53"
    networks:
      - name: "{{ traefik_network_name }}"
        ipv4_address: "{{ traefik_controller_ipv4 }}"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
      # - "53:53"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"