---
- name: Create a network
  docker_network:
    name: "{{ traefik_network_name }}"
    driver: bridge
    ipam_config:
      - subnet: 172.18.0.0/24

- name: Spawn traefik
  docker_container:
    name: "{{ container_name }}"
    image: "traefik:v2.8"
    restart_policy: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      # - "--entrypoints.dns.address=:53"
    networks:
      - name: "{{ traefik_network_name }}"
        ipv4_address: "172.18.0.200"
    ports:
      - "80:80"
      - "8080:8080"
      # - "53:53"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"