---
- include_tasks: install_configs.yml
- name: Spawn Mosquitto
  docker_container:
    name: mqtt
    image: eclipse-mosquitto
    restart_policy: unless-stopped
    volumes:
      - "{{ automation_root}}/mqtt:/mosquitto"
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ automation_root}}/mqtt/config:/mosquitto/config"
      - "{{ automation_root}}/mqtt/data:/mosquitto/data"
      - "{{ automation_root}}/mqtt/log:/mosquitto/log"

    networks:
      - name: "{{ hass_network_name }}"
        ipv4_address: "{{ hass_mqtt_container_ipv4 }}"
    ports:
      - 1883:1883
      - 9001:9001